name: CI Pipeline

on:
  push:
    branches:
      - main
      - '**'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Typescript Check
      - name: Run Typescript Check
        run: npm run type-check
        continue-on-error: true

      # 5. Run ESLint
      - name: Run ESLint
        run: npm run lint || true

      # 6. Run Stylelint
      - name: Run Stylelint
        run: npm run lint:css || true

      # 7. Run Jest tests with coverage
      - name: Run Jest tests
        run: npm run test:coverage
        continue-on-error: true

      # 8. Upload coverage report
      - name: Upload coverage report
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage
